organization:
  name: "banking application"
build:
  version: "2.0"
accounts:
  message: "Hey, welcome to EazyBank Common configuration"
  contactDetails:
    name: "Reine - Product Owner"
    email: "{cipher}2ddb40429290d9c240a937a16c264495660b53576a3466ea00ca7fad791016d8"  
  


    
